# Generated by Django 3.2.4 on 2023-09-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signin',
            new_name='signup',
        ),
    ]
