# Generated by Django 3.2.4 on 2023-09-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_signin_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Name',
            new_name='User',
        ),
    ]
