# Generated by Django 3.2.4 on 2023-09-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_name_signup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='joins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Mobile', models.IntegerField(null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
