# Generated by Django 3.2.4 on 2023-09-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_category_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dprice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
