# Generated by Django 3.2.4 on 2023-09-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20230920_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_mob',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
