# Generated by Django 3.2.4 on 2023-09-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_event_event_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spic', models.ImageField(null=True, upload_to='static/slider/')),
                ('sdate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
