# Generated by Django 3.2.4 on 2023-09-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230920_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='booknow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, null=True)),
                ('event_name', models.CharField(max_length=400, null=True)),
                ('event_picture', models.CharField(max_length=400, null=True)),
                ('speaker_name', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('hotel', models.CharField(max_length=200, null=True)),
                ('speaker_picture', models.CharField(max_length=400, null=True)),
                ('event_date', models.CharField(max_length=100, null=True)),
                ('event_price', models.CharField(max_length=500, null=True)),
                ('booking_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='uname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='upic',
            field=models.ImageField(null=True, upload_to='static/profile'),
        ),
    ]
