# Generated by Django 4.2.5 on 2023-10-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20230921_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='videogallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlink', models.TextField(null=True)),
                ('vdate', models.DateField()),
                ('event_des', models.TextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
    ]
